version: "3.8"

services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "80:80"
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:80"
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:latest
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always

  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: .
    command: celery -A notification_service worker -l info
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data:
