# Generated by Django 4.0.6 on 2022-07-29 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Телефон клиента', max_length=11)),
                ('operator_code', models.CharField(help_text='Код оператора', max_length=10)),
                ('tag', models.CharField(blank=True, help_text='Произвольный тег', max_length=200, null=True)),
                ('time_zone', models.CharField(help_text='Часовой пояс', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='Дата и время запуска рассылки')),
                ('text', models.TextField(help_text='Текст сообщения для доставки клиенту')),
                ('attribute', models.CharField(help_text='Свойство клиетов', max_length=255)),
                ('end_time', models.DateTimeField(help_text='Время окончания рассылки')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(help_text='Дата и время создания/отправки')),
                ('status', models.CharField(choices=[('Sent', 'Отправлено'), ('Waiting', 'Ожидает отправки'), ('Wrong', 'Не доставлено')], help_text='Статус отправки', max_length=255)),
                ('client', models.ForeignKey(help_text='Клиент', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.client')),
                ('mailing', models.ForeignKey(help_text='Рассылка', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.mailing')),
            ],
        ),
    ]
