# Generated by Django 4.0.6 on 2022-07-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(help_text='Телефон клиента', max_length=11, unique=True),
        ),
    ]
